---
title: "杭州至北京2018年1月1日余票" 
author: "Rain.Wei"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`" 
output: 
    github_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error = FALSE)  
library(RSelenium) 
library(rvest) 
library(tidyverse) 
library(stringr) 
library(methods)
```


## 启动Selenium Web Driver  

```{r}
# Run a server for example using Docker
# docker run -d -p 4445:4444 selenium/standalone-firefox:2.53.1
# Use a debug image with a VNC viewer if you wish to view the browser
# docker run -d -p 5901:5900 -p 127.0.0.1:4445:4444 --link http-server selenium/standalone-firefox-debug:2.53.1
# See Docker vignette for more detail or run a Selenium Server manually.
remDr <- remoteDriver(remoteServerAddr = "localhost" 
                      , port = 4445L 
                      , browserName = "chrome" 
                      ) 
remDr$open(silent = TRUE)  
```

```{r}
remDr$navigate('https://kyfw.12306.cn/otn/leftTicket/init') 

```

# Input Start Station and Arrival Station  

```{r} 
Sys.sleep(1 + runif(1)) 
elem.fromStation <- remDr$findElement(using = 'xpath', '//*[@id="fromStationText"]')
elem.fromStation$clickElement() 
elem.fromStation$sendKeysToElement(list("杭州"))
Sys.sleep(1 + runif(1))
elem.city.hangzhou <- remDr$findElement(using = 'xpath', '//*[@id="citem_1"]/span[1]')
elem.city.hangzhou$clickElement() 
Sys.sleep(1 + runif(1))
elem.toStation <- remDr$findElement(using = 'xpath', '//*[@id="toStationText"]') 
elem.toStation$sendKeysToElement(list("北京")) 
Sys.sleep(1 + runif(1)) 
elem.city.beijing <- remDr$findElement(using = 'xpath', '//*[@id="citem_2"]') 
elem.city.beijing$clickElement() 
```

# Input Start Date    

```{r}
Sys.sleep(1 + runif(1)) 
elem.date_input <- remDr$findElement(using = 'xpath', '//*[@id="train_date"]') 
elem.date_input$clickElement() 
Sys.sleep(1 + runif(1)) 
elem.date_20180101 <- remDr$findElement(using = 'xpath', 
                                        '/html/body/div[30]/div[2]/div[2]/div[1]/div') 
elem.date_20180101$clickElement() 
```

# Click Botton of Quering Tickets

```{r}
Sys.sleep(1 + runif(1)) 
elem.query_tickets <- remDr$findElement(using = 'xpath', '//*[@id="query_ticket"]') 
elem.query_tickets$clickElement() 
```

# Download Tickets Table


```{r} 
# Scroll to the bottom and wait 3 seconds 
remDr$executeScript('window.scrollTo(0, document.body.scrollHeight);', args = list("dummy")) 
Sys.sleep(1 + runif(1)) 
page_12306_source <- remDr$getPageSource() 
page_12306_source_html <- read_html(page_12306_source[[1]])

```

```{r}
tickets_table <- page_12306_source_html %>% 
    html_node('div#t-list.t-list') %>% 
    html_node('table') %>% 
    html_table(fill = TRUE)
```

```{r tickects table cleaning} 

#  [\u4e00-\u9fff]+  match any Chinese Characters 

tickets_table.clean <- tickets_table %>% 
    set_names(c('trainNo', 'fromTo', 'timeSchedule', 'during1', 
                'bussinessTickets', 'firstClass', 'secondClass', 
                'superSoftBed', 'softBed', 'crhBed', 'hardBed', 
                'softChair', 'hardChair', 'stand', 'other', 'remarks')) %>% 
    filter(!is.na(trainNo)) %>% 
    mutate(
        trainNo = str_extract(trainNo, "[A-Z]\\d+"), 
        fromTo = sub('查看票价', '', str_extract(fromTo, "查看票价[\u4e00-\u9fff]+")), 
        theDayOrNext =  str_split_fixed(during1, '\\d{2}:\\d{2}', 4)[,4] 
    )  
train_schedule <- str_extract_all(tickets_table.clean$during1, '\\d{2}:\\d{2}', 3) %>% 
    as.data.frame() %>% 
    set_names('start', 'arrival', 'during')

tickets_table.clean <- cbind(tickets_table.clean, train_schedule) %>% 
    select(-timeSchedule, -during1)
knitr::kable(tickets_table.clean) 
``` 


```{r}
remDr$close() 

```



